resolver: lts-8.11

flags: {}

extra-package-dbs: []

extra-deps:
  - composite-aeson-0.3.0.0
  - composite-base-0.3.0.0
  - composite-opaleye-0.3.0.0
  - hodor-model-0.0.0.1
  - servant-0.10
  - servant-client-0.10
  - servant-server-0.10

packages:
- '.'
- '../hodor-model'
