name:                hodor-migrate
version:             0.0.0.1
synopsis:            Data model and common types/functions for hodor
description:         Composite database model and common types for hodor
homepage:            https://github.com/jkachmar/hodor#readme
license:             MIT
author:              jkachmar
copyright:           2017 Joe Kachmar
category:            Web

default-extensions:
  - FlexibleContexts
  - NoImplicitPrelude
  - OverloadedStrings
  - QuasiQuotes
  - TemplateHaskell

dependencies:
  - base              >= 4.7 && < 5
  - classy-prelude    >= 1.2 && < 1.3
  - postgresql-simple >= 0.5 && < 0.6
  - refurb            >= 0.2 && < 0.3

ghc-options:
  - -Wall
  - -Werror

executables:
  hodor-migrate:
    source-dirs:      src
    main:             Main.hs
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N
